spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  zipkin.base-url: ${ZIPKIN_SERVICE}
auth0:
  audience: ${OAUTH_AUDIENCE}
  domain: ${OAUTH_DOMAIN}
