server:
  port: 8021
spring:
  application.name: users
  profiles.active: dev
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${auth0.domain}/