spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
  zipkin.base-url: ${ZIPKIN_SERVICE}
