spring:
  application.name: gateway
  profiles.active: dev
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
    instances:
      users:
        baseConfig: default
      games:
        baseConfig: default
      search:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s