server.port: 9999
spring:
  zipkin.base-url: ${ZIPKIN_SERVICE}
  cloud:
    gateway:
      routes:
        - id: users
          uri: ${USERS_SERVICE}
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - CircuitBreaker=users
        - id: games
          uri: ${GAMES_SERVICE}
          predicates:
            - Path=/game/**
          filters:
            - StripPrefix=1
            - CircuitBreaker=games
        - id: search
          uri: ${SEARCH_SERVICE}
          predicates:
            - Path=/search
          filters:
            - CircuitBreaker=search