server.port: 9991
spring:
  zipkin.base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: users
          uri: http://localhost:8021
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - CircuitBreaker=users
        - id: games
          uri: http://localhost:8022
          predicates:
            - Path=/game/**
          filters:
            - StripPrefix=1
            - CircuitBreaker=games
        - id: search
          uri: http://localhost:8100
          predicates:
            - Path=/search
          filters:
            - CircuitBreaker=search
