server.port: 9991
spring:
  zipkin.base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: users
          uri: http://localhost:8021
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<path>.*), /$\{path}
            - CircuitBreaker=users
        - id: search
          uri: http://localhost:8100
          predicates:
            - Path=/search
          filters:
            - CircuitBreaker=search
