apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: felixstumvoll/gamelib-gateway
          env:
            - name: ZIPKIN_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: zipkin-config
                  key: zipkin-service
            - name: USERS_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: users-service
            - name: SEARCH_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: search-service
          resources:
            limits:
              memory: "500Mi"
              cpu: "1"
          ports:
            - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - port: 9999
      targetPort: 9999
