apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  users-service: http://users-service:8021
  games-service: http://games-service:8022
  search-service: http://search-service:8100
