spring:
  datasource:
    url: jdbc:h2:file:./data/games
    username: sa
    password: root
    driverClassName: org.h2.Driver
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  zipkin.base-url: http://localhost:9411