apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
spec:
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: felixstumvoll/gamelib-search
          env:
            - name: USERS_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: search-config
                  key: users-service
            - name: GAMES_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: search-config
                  key: games-service
            - name: ZIPKIN_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: zipkin-config
                  key: zipkin-service
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8100
            initialDelaySeconds: 100
          ports:
            - containerPort: 8100
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: search-service
  ports:
    - port: 8100
      targetPort: 8100
