apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: felixstumvoll/gamelib-users
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: users-db-config
                  key: db-name
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: users-config
                  key: db-url
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: db-password
            - name: ZIPKIN_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: zipkin-config
                  key: zipkin-service
            - name: OAUTH_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: oauth-config
                  key: oauth-audience
            - name: OAUTH_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: oauth-config
                  key: oauth-domain
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8021
            initialDelaySeconds: 100
          ports:
            - containerPort: 8021
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users-service
  ports:
    - port: 8021
      targetPort: 8021
