apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-service
spec:
  selector:
    matchLabels:
      app: games-service
  template:
    metadata:
      labels:
        app: games-service
    spec:
      containers:
        - name: games-service
          image: felixstumvoll/gamelib-games
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: games-db-config
                  key: db-name
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: games-config
                  key: db-url
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: games-db-secret
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: games-db-secret
                  key: db-password
            - name: ZIPKIN_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: zipkin-config
                  key: zipkin-service
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 8021
---
apiVersion: v1
kind: Service
metadata:
  name: games-service
spec:
  selector:
    app: games-service
  ports:
    - port: 8021
      targetPort: 8021
